# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: '1. xxx'
    errorActionPreference: 'stop'
    failOnStderr: true

# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
- task: PowerShell@2
  inputs:
    script:  dir | Out-Host  
  displayName: '2. xxx'

- task: PowerShell@2
  displayName: '3. xxxx'
  targetType: 'Inline'
    script: |
      dir | Out-Host  
    errorActionPreference: 'stop'
    failOnStderr: true
    pwsh: true

- task: PowerShell@2
  inline:
    script:  dir | Out-Host  
  displayName: '2. xxx'

# Using the script shortcut syntax
- script: dir | Out-Host 
  displayName: '3. xxx'
