# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    echo Hello, world!
    dir
  displayName: '1. xxx'

- task: PowerShell@2
  displayName: '2. xxx multiline'
  inputs:
    targetType: inline
    script: |
      dir | Out-Host

- task: PowerShell@2
  displayName: '3. xxx'
  inputs:
      targetType: inline
      script:  dir | Out-Host  
